app/blueprints/auth.py
from flask import render_template, flash, redirect, url_for, Blueprint
from flask_login import login_user, logout_user, login_required, current_user

from app.extends import db
from app.forms import LoginForm, RegisterForm
from app.models import User
from app.utils import redirect_back

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('chat.home'))
    form = LoginForm()
    if form.validate_on_submit():
        email = form.email.data.lower()
        password = form.password.data
        remember = form.remember.data
        user = User.query.filter_by(email = email).first()
        if user is not None:
            if user.verify_password(password):
                login_user(user, remember)
                return redirect(url_for('chat.home'))
        flash('Invalid username or password.', 'warning')
    return render_template('auth/login.html', form=form)


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logout success.', 'info')
    return redirect_back()


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('chat.home'))

    form = RegisterForm()
    if form.validate_on_submit():
        email = form.email.data.lower()
        username = form.username.data
        password = form.password.data
        about = form.about.data
        if User.query.filter_by(email = email).first():
            flash('This email have been registered, please log in.')
        elif User.query.filter_by(username = username).first():
            flash('Username have been taken, choose another one.')
        else:
            user = User(username=username, email=email, about=about)
            user.set_password(password)
            user.generate_email_hash()
            db.session.add(user)
            db.session.commit()
            flash('User Created.', 'success')
            login_user(user, remember=True)
            return redirect(url_for('chat.home'))
    return render_template('auth/register.html', form=form)

app/blueprints/chat.py
from datetime import datetime

from flask import Blueprint, render_template, current_app, request
from flask_login import current_user
from flask_socketio import emit, join_room, rooms, leave_room

from app.extends import socketio, db, logger
from app.forms import RoomForm
from app.models import Message, User, Room

chat_bp = Blueprint('chat', __name__)

online_rooms = []  # set
room = Room('chat')
online_rooms.append(room)

online_users = []
user_to_sid = {}  # 映射username to session.id
sid_to_user = {}


@chat_bp.route('/')
def home():
    form = RoomForm()
    amount = current_app.config['MESSAGE_PER_PAGE']
    messages = Message.query.filter_by(in_room=1, room_name='chat').order_by(Message.timestamp.asc())[-amount:]

    return render_template('home.html', messages=messages, form=form, mode=1)


# AJAX message interface
@chat_bp.route('/chatroom/<room_name>', methods=['GET'])
def room_message(room_name):
    amount = current_app.config['MESSAGE_PER_PAGE']
    messages = Message.query.filter_by(in_room=1, room_name=room_name).order_by(Message.timestamp.asc())[-amount:]
    return render_template('chat/_messages.html', messages=messages, mode=1)


# experimental p2p chat
@chat_bp.route('/p/<username>')
def private_chat(username):
    # return redirect('http://127.0.0.1/p/' + uuid)
    sid = user_to_sid[username]
    # BUG: User A and B will both join the room opposite, so one con only see
    # messages sent by himself. In order to receive messages, he must back to
    # his private room. What's more, if more than one user send private
    # messages to A, A will see messages from different users are mixed.
    # So such a feature is like a message board instead of a private p2p chat.
    # TODO: Use a (id, id) pair as the identifier of a p2p room
    return room_message(sid)


# user about
@chat_bp.route('/a/<username>')
def user_about(username):
    about = getUserFromUsername(username).about
    data = {'about': about, 'sid': user_to_sid[username]}
    return data


@socketio.on('connect')
def connect():
    global online_users
    user = current_user._get_current_object()
    if current_user.is_authenticated and user not in online_users:
        print(online_users)
        online_users.append(user)
        print(online_users)
        user_to_sid[user.username] = request.sid
        sid_to_user[request.sid] = user.username
        logger.info("%s is connected." % user.username)
    logger.info("online users: {}".format(online_users))
    join_room('chat')
    getRoomFromRoomname('chat').add_user(request.sid)
    emit_users_info(request.sid)


@socketio.on('disconnect')
def disconnect():
    global online_users
    if current_user.is_authenticated and current_user in online_users:
        try:
            online_users.remove(current_user)
            del user_to_sid[current_user.username]
            del sid_to_user[request.sid]
            logger.info("%s is disconnected." % current_user.username)
            logger.info("online users: {}".format(online_users))
        except Exception as e:
            logger.error(e)

    leave_room('chat')
    getRoomFromRoomname('chat').remove_user(request.sid)
    emit_users_info(request.sid)


@socketio.on('new message')
def new_message(message_body):
    message = Message(author=current_user._get_current_object(), body=message_body['body'],
                      room_name=message_body['room_name'], timestamp=datetime.utcnow())
    db.session.add(message)
    db.session.commit()

    # send to sender it self
    emit('new message',
         {'message_html': render_template('chat/_message.html', message=message, mode=0, flag=0),
          'message_body': message_body,
          'room_name': message_body['room_name'],
          'gravatar': current_user.gravatar,
          'username': current_user.username,
          'user_id': current_user.id})
    # send to other one

    emit('new message',
         {'message_html': render_template('chat/_message.html', message=message, mode=0, flag=1),
          'message_body': message_body,
          'room_name': message_body['room_name'],
          'gravatar': current_user.gravatar,
          'username': current_user.username,
          'user_id': current_user.id},
         to=message_body['room_name'], skip_sid=request.sid)


@socketio.on('join room')
def join(room_name):
    join_room(room_name)
    room = Room(room_name)
    if room not in online_rooms:
        online_rooms.append(room)
    getRoomFromRoomname(room_name).add_user(request.sid)
    emit('joined_room', {'room_name': room_name, 'user_name': current_user.username})
    emit_users_info(request.sid)


#
# webrtc
#
# 'webrtc connect' -> user click video button, ready to start a video chat.
@socketio.on('webrtc connect')
def webrtc_connect(data):
    room = data['room_name']
    user_amount = getRoomFromRoomname(room).length()
    logger.info("WebRTC connected. sid: {}, room: {}, user amount: {}".format(request.sid, room, user_amount))

    if user_amount < 3:
        # the first and second user will trigger
        logger.info('sid: {} joined video sharing.'.format(request.sid))
        emit('webrtc joined',
             {"room": room, "sid": request.sid},
             room=room, skip_sid=request.sid)
        if user_amount > 1:
            # the second user ~
            logger.info('webrtc ready.')
            emit('webrtc ready',
                 {"room": room, "sid": request.sid},
                 room=room, skip_sid=request.sid)
    else:
        # the third user ~
        logger.info('sid: {} joined, but room is full, exiting'.format(request.sid))
        leave_room(room)
        emit('full')  # the third user will be alerted and stop streaming


@socketio.on('webrtc data')
def webrtc_data(data):
    logger.info('Message from {}: {}'.format(request.sid, data))
    emit('webrtc data', data["data"], room=data["room_name"], skip_sid=request.sid)


def emit_users_info(sid):
    r = rooms(sid=sid)
    logger.info("{} now is in: {}".format(current_user.username, r))
    emit('users info',
         {'amount': len(online_users),
          'users': render_template('chat/_users.html', users=online_users),
          'rooms_amount': len(r),
          'rooms': render_template('chat/_rooms.html', rooms=r)}, broadcast=True)


def getUserFromUsername(username):
    global online_users
    flag = 0
    user = User()
    for u in online_users:
        if u.username == username:
            flag = 1
            user = u
            break
    if flag == 1:
        return user
    else:
        return None


def getRoomFromRoomname(roomname):
    global online_rooms
    flag = 0
    room: Room('chat')
    for r in online_rooms:
        if r.name == roomname:
            flag = 1
            room = r
            break
    if flag == 1:
        return room
    else:
        return None

app/templates/base.html
{% from 'bootstrap/nav.html' import render_nav_item %}
<!DOCTYPE html>
<html>
<head>
    {% block head %}
        <meta charset="utf-8">
        <title>{% block title %}Socket IO Chat{% endblock %}</title>
        <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='apple-touch-icon.png') }}">
        <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='favicon-32x32.png') }}">
        <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='favicon-16x16.png') }}">
        <link rel="manifest" href="{{ url_for('static', filename='site.webmanifest') }}">
        <link rel="mask-icon" href="{{ url_for('static', filename='safari-pinned-tab.svg') }}" color="#5bbad5">
        <meta name="msapplication-TileColor" content="#da532c">
        <meta name="theme-color" content="#ffffff">
        {% block styles %}
            <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css' ) }}">
            {{ bootstrap.load_css() }}
        {% endblock %}
    {% endblock %}
</head>
<body>
<nav>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">

            <a class="navbar-brand" href="{{ url_for('chat.home') }}">SocketIO Chat</a>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                    <a class="nav-link" href="{{ url_for('auth.logout', next=request.full_path) }}">Logout</a>
                {% else %}
                    <a class="nav-link" href="{{ url_for('auth.register', next=request.full_path) }}">Register</a>
                    <a class="nav-link" href="{{ url_for('auth.login', next=request.full_path) }}">Login</a>
                {% endif %}
            </ul>
        </div>
    </nav>
</nav>

<main>
    {% block main %}
        {% for message in get_flashed_messages() %}
            <div class="container">
                <div class="alert alert-primary justify-content-md-center" role="alert">{{ message }}</div>
            </div>
        {% endfor %}
        {% block content %}{% endblock %}
    {% endblock %}
</main>
{% block footer_ %}
    <footer>
        {% block footer %}
            {% include "footer.html" %}
        {% endblock %}
    </footer>
{% endblock %}
{% block scripts %}
    {{ bootstrap.load_js() }}
    {{ JSGlue.include() }}
{% endblock %}
</body>
</html>

app/templates/chat.html
{% extends 'base.html' %}
{% block title %}
    <title>Flask-SocketIO-Chat</title>
{% endblock %}
{% block content %}
    <h1>Room: {{ room }}</h1>
    <textarea id="chat" cols="80" rows="20"></textarea><br><br>
    <input id="text" size="80" placeholder="Enter your message here"><br><br>
    <a href="#" onclick="leave_room();">Leave this room</a>
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='js/socket.js') }}"></script>
{% endblock %}

app/templates/chatroom.html
{% extends 'base.html' %}
{% block title %}
    Flask-SocketIO-Chat
{% endblock %}
{% block content %}
    <div class="container">
        <div class="page-header">
            <h1 class="display-3">Room: {{ room }}</h1>
        </div>
        <textarea class="form-control" id="chat" cols="80" rows="20"></textarea><br><br>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">Message: </span>
            </div>
            <input id="text" type="text" class="form-control">
        </div>
        <a href="#" onclick="leave_room();">Leave this room</a>
    </div>
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='js/socket.js') }}"></script>
{% endblock %}

app/templates/footer.html
<p class="text-center">
    <small> &copy; 2021 Magicwenli
    </small>
</p>

app/templates/home.html
{% extends 'base.html' %}
{% block title %}
    SocketIO Chat
{% endblock %}
{% block main %}
    <div class="layout">
        <div class="sidebar py-xl-4 py-3 px-xl-4 px-3">
            {% include 'chat/_sidebar.html' %}
        </div>
        <div class="main px-xl-5 px-lg-4 px-3">
            {% include 'chat/_chatbody.html' %}
        </div>
    </div>
    {% include "chat/_join_room.html" %}

{% endblock %}
{% block scripts %}
    {{ super() }}
{# <script type="text/javascript" src="{{ url_for('static',filename='js/socket.io.min.js') }}"></script> #}
    <script src="https://cdn.bootcdn.net/ajax/libs/socket.io/4.0.1/socket.io.min.js"></script>
    <script src="https://cdn.bootcdn.net/ajax/libs/adapterjs/0.15.5/adapter.min.js"></script>
    {{ moment.include_moment(local_js="https://cdn.bootcdn.net/ajax/libs/moment.js/2.29.1/moment-with-locales.min.js") }}
    <script type="text/javascript" src="{{ url_for('static',filename='js/script.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='js/socket.js') }}"></script>
{% endblock %}
{%  block footer_ %}{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% block title %}
    <title>Choose Group</title>
{% endblock %}
{% block content %}
    <div class="container h-100">
        <div class="row h-100 page-header justify-content-center align-items-center">
            <h1>Enter the Group Name you want to join.</h1>
        </div>
        <div class="row h-100 justify-content-center align-items-center">
            {{ render_form(form,method="post") }}
        </div>
    </div>
{% endblock %}

app/templates/selete_room.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% block title %}
    <title>Choose Group</title>
{% endblock %}
{% block content %}
    <div class="container h-100">
        <div class="row h-100 page-header justify-content-center align-items-center">
            <h1>Enter the Group Name you want to join.</h1>
        </div>
        <div class="row h-100 justify-content-center align-items-center">
            {{ render_form(form,method="post") }}
        </div>
    </div>
{% endblock %}